version: '3'
volumes:
  postgres_data:
  public_data:
  tmp_data:
  log_data:
services:
  app:
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/sample_app
      - public_data:/sample_app/public
      - tmp_data:/sample_app/tmp
      - log_data:/sample_app/log
  
  web:
    build:
      context: .
      dockerfile: ./Docker/web/Dockerfile
    volumes:
      - public_data:/sample_app/public
      - tmp_data:/sample_app/tmp
    ports:
      - 80:80
    depends_on:
      - app
